name: Clang-Tidy

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.c"
      - "**/*.cc"
      - "**/*.cpp"
      - "**/*.cxx"
      - "**/*.h"
      - "**/*.hh"
      - "**/*.hpp"
      - "**/*.hxx"
      - ".clang-tidy"

permissions:
  contents: read

jobs:
  clang-tidy-diff:
    uses: anolishq/.github/.github/workflows/clang-tidy-diff.yml@9869a5f4bee7da9c7c1dc9bae033cd0137c4801d # clang-tidy-diff
    with:
      configure-preset: ci-linux-release
